---
name: POE-Component-IRC-Plugin-WWW-CPAN
version: 0.0101
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: access http://search.cpan.org/ from IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.002
  POE::Component::WWW::CPAN: 0.0101
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::CPAN:
    file: lib/POE/Component/IRC/Plugin/WWW/CPAN.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
